config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  root 'welcome#index', via: :get

  get 'photo/:id' => 'js#photo'
  post 'positions' => 'js#pages'

  resources :users, only: :none do
    resources :books do
      resources :pages
    end
  end

end

app/views/pages/_card.html.haml
.row
  .col-xs-1.handle
    %i.fa.fa-arrows-v
  .col-xs-1
    = image_tag page.image_url(1)
  .col-xs-8.page-text
    = page.text
  .col-xs-2
    = link_to 'View', user_book_page_path(page.book.author, page.book, page), class: 'btn btn-warning'

app/views/pages/_form.html.haml
= form_for [@user, @book, @page] do |f|
  .field
    = f.label :flickr_photo_id, 'Picture (Flickr Photo ID)'
    = f.number_field :flickr_photo_id, class: 'form-control', autofocus: (action_name == 'new')
  .field
    = f.label :text, 'Words'
    = f.text_area :text, class: 'form-control', rows: 8, autofocus: (action_name == 'edit')
  %button.btn.btn-warning{:type => "submit"}
    = submit_button

app/views/pages/edit.html.haml
.col-sm-offset-2.col-sm-8
  %h3 Edit Page
  = render partial: 'form', locals: { submit_button: 'Update' }

  %h4 Photo Preview
  .photo-preview
    =image_tag @page.image_url(6)

app/views/pages/index.html.haml
.row
  .col-sm-8.col-sm-offset-2
    %h3 Edit Page Order
    %ul#page-sort
      - @pages.each do |page|
        - cache(page) do
          = content_tag_for(:li, page, class: 'well') do
            = render partial: 'card', locals: { page: page }

.row.last-row
  .col-sm-8.col-sm-offset-2
    = link_to "Back to #{@book.title}", user_book_path(@user, @book), class: 'btn btn-warning'

app/views/pages/new.html.haml
.col-sm-offset-2.col-sm-8
  %h3 Add a Page
  = render partial: 'form', locals: { submit_button: 'Create' }

  %h4 Photo Preview
  .photo-preview

app/views/pages/show.html.haml
.row
  .page-text.well.col-sm-8.col-sm-offset-2<
    = @page.text

.row.photo-carousel
  .col-xs-2
    .page-arrow
      - if previous_page = @page.previous_page
        = link_to user_book_page_path(@user, @book, previous_page) do
          %i.fa.fa-chevron-left.fa-3x
  .page-image.col-xs-8
    =image_tag @page.image_url(9)
  .col-xs-2
    .page-arrow
      - if next_page = @page.next_page
        = link_to user_book_page_path(@user, @book, next_page) do
          %i.fa.fa-chevron-right.fa-3x

.row
  .col-sm-8.col-sm-offset-2
    %h5
      = link_to "#{@book.title}", user_book_path(@user, @book)
      by
      = link_to "@#{@user.username}", user_books_path(@user)

- if current_user?(@user)
  .row
    .col-sm-8.col-sm-offset-2
      = link_to "Edit Page", edit_user_book_page_path(@user, @book, @page), class: 'btn btn-warning'
      = link_to "Add another Page", new_user_book_page_path(@user, @book), class: 'btn btn-warning'
      = link_to "Delete Page", { action: :destroy, id: @page.id }, method: :delete, data: { confirm: destroy_page_confirmation }, class: 'btn btn-danger pull-right'

.row.page-number
  = "#{@page.position} / #{@book.length}"