config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  root 'welcome#index', via: :get

  get 'photo/:id' => 'js#photo'
  post 'positions' => 'js#pages'

  resources :users, only: :none do
    resources :books do
      resources :pages
    end
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'

  has_many :pages, -> { order 'position' }, dependent: :destroy

  validates :author, presence: true
  validates :title, presence: true
  validates :title_color, presence: true

  scope :published, -> do
    joins(:pages).uniq
  end

  def cover_page
    pages.first || NullPage.new
  end

  def length
    pages.count
  end

  def next_position
    (pages.last || NullPage.new).position + 1
  end

  def self.featured
    self.where(featured: true).limit(12).order("RANDOM()")
  end

  def self.title_colors
    ['Gray',
     'Aqua',
     'Black',
     'Blue',
     'Fuchsia',
     'Green',
     'Lime',
     'Maroon',
     'Navy',
     'Olive',
     'Purple',
     'Red',
     'Silver',
     'Teal',
     'White',
     'Yellow']
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_user
  before_action :find_book, except: [:index, :new, :create]

  def index
    @books = @user == current_user ? @user.books : @user.books.published
  end

  def new
    @book = @user.books.new
  end

  def create
    @book = @user.books.new(book_params)
    if @book.save
      flash.clear
      redirect_to user_book_path(@user, @book)
    else
      flash[:alert] = @book.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
    fresh_when(@book)
  end

  def edit
  end

  def update
    if @book.update_attributes(book_params)
      flash.clear
      redirect_to user_book_path(@user, @book)
    else
      flash[:alert] = @book.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @book.destroy
      flash.clear
      redirect_to user_books_path(@user)
    else
      flash[:alert] = @book.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :title_color)
  end

  def find_book
    @book = @user.books.find(params[:id])
  end
end

app/views/books/_form.html.haml
= form_for [@user, @book] do |f|
  .field
    = f.label :title
    = f.text_field :title, class: 'form-control', autofocus: (action_name == 'new')
  .field
    = f.label :title_color
    = f.select :title_color, Book.title_colors, { }, class: 'form-control'
  %button.btn.btn-warning{:type => "submit"}
    = submit_button

app/views/books/_list.html.haml
.book-list
  - books.each do |book|
    .book-covers
      - cache([book, profile_page?]) do
        %h4= book.title
        %h5= link_to "@#{book.author.username}", user_books_path(book.author) unless profile_page?
        = link_to image_tag(book.cover_page.image_url(5)), user_book_path(book.author, book)
      - if current_user?(book.author)
        .edit-double Edit
        = link_to 'Edit', edit_user_book_path(book.author, book), class: 'btn btn-warning'

app/views/books/edit.html.haml
.col-sm-offset-2.col-sm-8
  %h3= "Edit #{@book.title}"
  = render partial: 'form', locals: { submit_button: 'Update' }

  %h3 Advanced Options
  = link_to "Order Pages", user_book_pages_path(@user, @book), class: 'btn btn-warning'
  = link_to "Delete #{@book.title}", { action: :destroy, id: @book.id }, method: :delete, data: { confirm: destroy_book_confirmation }, class: 'btn btn-danger pull-right'

app/views/books/index.html.haml
.row
  .col-sm-8.col-sm-offset-2
    %h3
      = current_user?(@user) ? "My Books" : "@#{@user.username}'s Books"

.row
  .col-sm-8.col-sm-offset-2
    = render partial: 'list', locals: { books: @books }

- if current_user?(@user)
  .row.new-book
    .col-sm-8.col-sm-offset-2
      = link_to 'Create a New Book', new_user_book_path(@user), class: 'btn btn-warning'

app/views/books/new.html.haml
.col-sm-offset-2.col-sm-8
  %h3 Set Up a New Book
  = render partial: 'form', locals: { submit_button: 'Create' }

app/views/books/show.html.haml
.row
  .cover-page.col-sm-8.col-sm-offset-2
    -first_page_path = @book.pages.first ? user_book_page_path(@user, @book, @book.pages.first) : '#'
    =link_to image_tag(@book.cover_page.image_url), first_page_path
    %h3
      %font{color: @book.title_color}
        =@book.title
    .by-line
      %h5
        written by
        =link_to "@#{@user.username}", user_books_path(@user)

-if current_user?(@user)
  .cover-page.col-sm-8.col-sm-offset-2
    =link_to "Add a Page", new_user_book_page_path(@user, @book), class: 'btn btn-warning'
    =link_to "Order Pages", user_book_pages_path(@user, @book), class: 'btn btn-warning'
    =link_to "Edit #{@book.title}", edit_user_book_path(@user, @book), class: 'btn btn-warning pull-right'